
name: dev.jonataserpa.net deployment

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
        
    workflow_dispatch:
        
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
            run: echo Building the app
            
    deploy-devolpment:
        runs-on: ubuntu-latest            
        environment: 
            name: dev
            url: https://dev.jonataserpa.net/
        needs: build    
        steps:
           - name: Repo checkout
             uses: actions/checkout@v1
           - name: Hostinger Deployment
             uses: easingthemes/ssh-deploy@main
             with:   
                SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
                ARGS: "-rlgoDzvc --delete"
                SOURCE: "/"
                REMOTE_HOST: ${{vars.REMOTE_HOST}}
                REMOTE_USER: ${{vars.REMOTE_USER}}
                REMOTE_PORT: ${{vars.REMOTE_PORT}}
                TARGET: ${{vars.TARGET}}

    deploy-homol:
        runs-on: ubuntu-latest            
        environment: 
            name: homol
            url: https://homol.jonataserpa.net/
        needs: deploy-homol    
        steps:
          - name: Repo checkout
            uses: actions/checkout@v1
          - name: Hostinger Deployment
            uses: easingthemes/ssh-deploy@main
            with:   
            SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "/"
            REMOTE_HOST: ${{vars.REMOTE_HOST}}
            REMOTE_USER: ${{vars.REMOTE_USER}}
            REMOTE_PORT: ${{vars.REMOTE_PORT}}
            TARGET: ${{vars.TARGET}}            
